services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  rag:
    build:
      context: .
      dockerfile: Dockerfile.rag
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=docs_support
      - DATA_DIR=/data
      - HF_HOME=/hf
      - TRANSFORMERS_CACHE=/hf/transformers
      - HUGGINGFACE_HUB_CACHE=/hf/hub
      - EMBED_LOCAL_FILES_ONLY=1
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./hf_cache:/hf
      - ./models:/models
      - ./data_dir:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - rag
    environment:
      - RAG_BASE_URL=http://rag:8001
    env_file:
      - .env
    ports:
      - "8000:8000"

