FROM nginx:alpine

COPY default.tmpl.conf /etc/nginx/conf.d/default.tmpl.conf
COPY nginx_entrypoint.sh /nginx_entrypoint.sh

RUN chmod +x /nginx_entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/nginx_entrypoint.sh"]
