services:
  qdrant:
    image: qdrant/qdrant:v1.18.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  rag:
    build:
      context: .
      dockerfile: Dockerfile.rag
    depends_on:
      - qdrant
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=docs_support
      - DATA_DIR=/data
      - HF_HOME=/hf
      - TRANSFORMERS_CACHE=/hf/transformers
      - HUGGINGFACE_HUB_CACHE=/hf/hub
      - EMBED_LOCAL_FILES_ONLY=1
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
    env_file:
      - .env
    ports:
      - "8001:8001"
    volumes:
      - ./hf_cache:/hf
      - ./data:/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - rag
    environment:
      - RAG_BASE_URL=http://rag:8001
    env_file:
      - .env
    ports:
      - "8002:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    depends_on:
      - backend
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN}
    ports:
      - "82:80"