FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.backend.txt /app/requirements.backend.txt
RUN pip install --no-cache-dir -r /app/requirements.backend.txt

COPY src /app/src

EXPOSE 8000

CMD ["uvicorn", "src.backend.api.facade.main:app", "--host", "0.0.0.0", "--port", "8000"]

